#!perl -w


###   UcdDataToPl - read in the ucd data binary file and emit it as a cpp with
#     the data as an initialized array.

use strict;
use Fcntl;
use FindBin;
use File::Spec;
use File::Path qw(make_path);
use Cwd 'abs_path';

my $repoRoot = abs_path(File::Spec->catdir($FindBin::Bin, "..", "..", ".."))
    or die "Unable to resolve repository root.\n";
my $inputDir = File::Spec->catdir($FindBin::Bin, "data");
my $outputDir = File::Spec->catdir($repoRoot, "generated", "runtime", "text", "Classification");

my $inputBin = File::Spec->catfile($inputDir, "UcdData.bin");
my $outputCpp = File::Spec->catfile($outputDir, "UcdData.cpp");

sysopen(BIN, $inputBin, O_RDONLY|O_BINARY) or die "Unable to open '$inputBin'.\n";
make_path($outputDir) or die "Unable to create '$outputDir'.\n" unless -d $outputDir;
open(CPP, ">" . $outputCpp) or die "Unable to write '$outputCpp'.\n";

print "Reading binary classification data from '$inputBin'.\n";
print "Writing c++ formatted data to '$outputCpp'.\n";


print CPP "// Copyright (c) Microsoft Corporation. All rights reserved.\n";
print CPP "// Licensed under the MIT License. See LICENSE in the project root for license information.\n";
print CPP "//+----------------------------------------------------------------------------\n";
print CPP "//\n";
print CPP "//  This file was generated by UcdDataToCpp.pl\n";
print CPP "//\n";
print CPP "//  DO NOT HAND MODIFY\n";
print CPP "//\n";
print CPP "//  Contents: Unicode data classification as an initialized binary array.\n";
print CPP "//\n";
print CPP "//-----------------------------------------------------------------------------\n";
print CPP "\n";
print CPP "#include \"precomp.h\"\n";
print CPP "\n";
print CPP "\n";
print CPP "const XUINT8 g_ucdDataBytes[] = \n";
print CPP "{\n";

# Read 16 bytes at a time

my $bytes      = "";
my $nBytes     = 0;
my $totalBytes = 0;

do
{
    $nBytes = sysread(BIN, $bytes, 16);
    $totalBytes += $nBytes;

    print CPP "    ";

    for (my $i=0; $i<$nBytes; $i++)
    {
        printf CPP "0x%02x, ", ord(substr($bytes, $i, 1));
    }

    print CPP "\n";

} while ($nBytes >= 1);

close(BIN);

print CPP "};\n";
close(CPP);

print "$totalBytes bytes processed.\n"

