<Project ToolsVersion="Current">
  <Import Project="..\GraphAugmentation.targets" />
  <ItemGroup>
    <ProjectReference Include="$(ProjectRoot)src\controls\dll\Microsoft.UI.Xaml.Controls.vcxproj">
      <Targets>GetTargetPathWithTargetPlatformMoniker</Targets>
    </ProjectReference>
    <ProjectReference Include="$(MuxControlsIdlPath)Microsoft.UI.Xaml.Controls.idl.vcxproj">
      <Targets>BuildGenerateSources;GetPackagingOutputs;GetTargetPathWithTargetPlatformMoniker</Targets>
    </ProjectReference>
    <ProjectReference Include="$(XcpPhonePath)\idl\phone.vcxproj">
      <Targets>BuildGenerateSources;GetPackagingOutputs;GetTargetPathWithTargetPlatformMoniker</Targets>
    </ProjectReference>
    <ProjectReference Include="$(XcpPath)\components\pch\prod\Microsoft.UI.Xaml.Precomp.vcxproj">
      <Targets>GetTargetFrameworks;GetTargetFrameworksWithPlatformForSingleTargetFramework</Targets>
    </ProjectReference>
    <ProjectReference Include="$(XamlDiagnosticsComponentPath)\idl\xamlom.vcxproj">
      <Targets>GetTargetFrameworks;GetTargetFrameworksWithPlatformForSingleTargetFramework</Targets>
    </ProjectReference>
    <ProjectReference Include="$(XcpPath)\core\parser\staticpch\Parser.pch.vcxproj">
      <Targets>GetTargetFrameworks;GetTargetFrameworksWithPlatformForSingleTargetFramework</Targets>
    </ProjectReference>
    <ProjectReference Include="$(XcpPath)\dxaml\idl\com\microsoft.ui.xaml-com.vcxproj">
      <Targets>BuildGenerateSources;GetPackagingOutputs;GetTargetPathWithTargetPlatformMoniker</Targets>
    </ProjectReference>
    <ProjectReference Include="$(XcpPath)\dxaml\idl\winrt\controls\Microsoft.ui.xaml.controls.controls.vcxproj">
      <Targets>BuildGenerateSources;GetPackagingOutputs;GetTargetPathWithTargetPlatformMoniker</Targets>
    </ProjectReference>
    <ProjectReference Include="$(XcpPath)\dxaml\idl\winrt\core\Microsoft.ui.xaml.coretypes.vcxproj">
      <Targets>BuildGenerateSources;GetPackagingOutputs;GetTargetPathWithTargetPlatformMoniker</Targets>
    </ProjectReference>
    <ProjectReference Include="$(XcpPath)\dxaml\idl\winrt\main\Microsoft.ui.xaml-main.vcxproj">
      <Targets>BuildGenerateSources;GetPackagingOutputs;GetTargetPathWithTargetPlatformMoniker</Targets>
    </ProjectReference>
    <ProjectReference Include="$(XcpPath)\dxaml\idl\winrt\merged\microsoft.ui.xaml.vcxproj">
      <Targets>GetTargetFrameworks;GetTargetFrameworksWithPlatformForSingleTargetFramework</Targets>
    </ProjectReference>
    <ProjectReference Include="$(XcpPath)\dxaml\idl\winrt\merged\private\Microsoft.UI.Xaml.vcxproj">
      <Targets>GetTargetPathWithTargetPlatformMoniker</Targets>
    </ProjectReference>
    <ProjectReference Include="$(XcpPath)\dxaml\manifest\manifest.vcxproj">
      <Targets>GetTargetPathWithTargetPlatformMoniker</Targets>
    </ProjectReference>
    <ProjectReference Include="$(XcpPath)\hostpalplatmisc.vcxproj">
      <Targets>GetTargetFrameworks;GetTargetFrameworksWithPlatformForSingleTargetFramework</Targets>
    </ProjectReference>
    <ProjectReference Include="$(XcpPath)\pal\debug\PALDebug.vcxproj">
      <Targets>GetTargetFrameworks;GetTargetFrameworksWithPlatformForSingleTargetFramework</Targets>
    </ProjectReference>
    <ProjectReference Include="$(ProjectRoot)eng\midl\gencompheadersandidl.vcxproj">
      <Targets>GetTargetPathWithTargetPlatformMoniker</Targets>
    </ProjectReference>
    <ProjectReference Include="$(ProjectRoot)eng\midl\genmrtheadersandidl.vcxproj">
      <Targets>GetTargetPathWithTargetPlatformMoniker</Targets>
    </ProjectReference>
    <ProjectReference Include="$(ProjectRoot)src\projection\Microsoft.WinUI.csproj">
      <Targets>GetTargetFrameworks;GetTargetPathWithTargetPlatformMoniker;GetNativeManifest;GetCopyToOutputDirectoryItems;GetTargetFrameworksWithPlatformForSingleTargetFramework</Targets>
    </ProjectReference>
    <ProjectReference Include="$(ProjectRoot)src\projection\private\Microsoft.WinUI.csproj">
      <Targets>GetTargetPathWithTargetPlatformMoniker</Targets>
    </ProjectReference>
  </ItemGroup>
</Project>
