name: Validate doc links

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check local links
        run: npx --yes unbroken --local-only
        working-directory: docs
        timeout-minutes: 10
